# Generated by Django 3.2.12 on 2022-02-24 19:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipe', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Instructions',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=1024)),
            ],
        ),
        migrations.AddField(
            model_name='chef',
            name='chef_id',
            field=models.CharField(default='-', max_length=255),
        ),
        migrations.AddField(
            model_name='recipe',
            name='cooking_time_minutes',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='recipe',
            name='description',
            field=models.CharField(default=None, max_length=4096, null=True),
        ),
        migrations.AddField(
            model_name='recipe',
            name='photo_url',
            field=models.URLField(default=None, null=True),
        ),
        migrations.AddField(
            model_name='recipe',
            name='preparation_time_minutes',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='recipe',
            name='serves',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='recipe',
            name='total_time_minutes',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='chef',
            name='chef_name',
            field=models.CharField(default='-', max_length=255),
        ),
        migrations.RemoveField(
            model_name='recipe',
            name='instructions',
        ),
        migrations.AddField(
            model_name='recipe',
            name='instructions',
            field=models.ManyToManyField(to='recipe.Instructions'),
        ),
    ]
