# Generated by Django 3.2.12 on 2022-02-24 19:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipe', '0003_auto_20220224_1924'),
    ]

    operations = [
        migrations.RenameField(
            model_name='instructions',
            old_name='name',
            new_name='line_item',
        ),
        migrations.RemoveField(
            model_name='ingredients',
            name='name',
        ),
        migrations.AddField(
            model_name='ingredients',
            name='line_item',
            field=models.CharField(default=None, max_length=1024, null=True),
        ),
    ]
