# Generated by Django 3.2.12 on 2022-02-24 22:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('recipe', '0005_auto_20220224_2129'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='recipe',
            name='chef',
        ),
        migrations.AddField(
            model_name='recipe',
            name='chef',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='recipe.chef'),
        ),
    ]
