# Generated by Django 3.2.12 on 2022-02-24 22:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipe', '0006_auto_20220224_2239'),
    ]

    operations = [
        migrations.AlterField(
            model_name='chef',
            name='chef_id',
            field=models.CharField(default=None, max_length=255),
        ),
        migrations.AlterField(
            model_name='chef',
            name='chef_name',
            field=models.CharField(default=None, max_length=255),
        ),
    ]
