# Generated by Django 3.2.12 on 2022-02-24 22:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipe', '0010_auto_20220224_2254'),
    ]

    operations = [
        migrations.AlterField(
            model_name='chef',
            name='chef_id',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='chef',
            name='chef_name',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
