# Generated by Django 3.2.12 on 2022-02-24 23:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('recipe', '0012_alter_recipe_chef'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='recipe',
            name='chef',
        ),
        migrations.AddField(
            model_name='chef',
            name='recipes',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='recipe.recipe'),
        ),
        migrations.AlterField(
            model_name='chef',
            name='chef_id',
            field=models.CharField(default=None, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='chef',
            name='chef_name',
            field=models.CharField(default=None, max_length=255, null=True),
        ),
    ]
