# Generated by Django 3.2.12 on 2022-02-24 23:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipe', '0013_auto_20220224_2300'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='chef',
            name='recipes',
        ),
        migrations.AddField(
            model_name='recipe',
            name='chef',
            field=models.ManyToManyField(to='recipe.Chef'),
        ),
    ]
