# Generated by Django 3.2.12 on 2022-03-02 20:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('recipe', '0017_alter_ingredient_name'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='recipe',
            options={'ordering': ['-id']},
        ),
    ]
